### ISSUE TITLE
[Question] Regarding Example

### ISSUE THREAD

**Issue by bh2smith** [tomusdrw/rust-web3#225] opened 2019-06-26 15:37 UTC
Hello, I am wondering if perhaps the readme for example is missing something?

I have cloned the project and followed the guide from `example/readme.md`. That is

```
ganache-cli -m "hamster coin cup brief quote trick stove draft hobby strong caught unable"
cargo run --example contract
```

Everything appears to compile fine, but the only thing appearing in ganache is a revert statement:

```
eth_sendTransaction

  Transaction: 0x21860b87e3f3085dd78c659042af9d214f3c8ce449a7886815c3b99fc8795390
  Contract created: 0x4d470146215d085c75767b717dbb8d3b4468f893
  Gas usage: 241727
  Block Number: 1
  Block Time: Wed Jun 26 2019 17:19:40 GMT+0200 (Central European Summer Time)
  Runtime Error: revert

eth_newBlockFilter
eth_getFilterChanges
```

The `cargo run` itself just appears to freeze/hang like so;

```
    Finished dev [unoptimized + debuginfo] target(s) in 2m 12s
     Running `target/debug/examples/contract`
```

I am still kinda new to rust, but have tried this with both rust versions `1.33.0` and `1.34.0`. After including a few print statements, it appears to be a hanging at `Contract::deploy` 

https://github.com/tomusdrw/rust-web3/blob/21cb38c7203a026f292d65059272b88e2050626e/examples/contract.rs#L18-L33

Not sure if I am doing something wrong or if there might be something out of date here...

**Comment by tomusdrw** [comment] 2019-07-09 15:43
Seems that the deployment code waits for `4` confirmations, and `ganache-cli` most likely does not mine blocks.
Could you try changing `confirmations(4)` to `confrimations(0)` and see if it works?

**Comment by tomusdrw** [comment] 2019-07-09 17:43
Actually deploying the contract should work fine, so the `revert` should not be there. It actually seems that the example deploys a `json` file instead of actual solidity bytecode.

**Comment by bh2smith** [comment] 2019-07-10 06:26
Interesting, I will play around with it some more and see what I can do about it.

**Comment by tomusdrw** [comment] 2019-07-10 10:15
Actually just realised it's a duplicate of #182 , let's continue there.

**Closed by tomusdrw** 2019-07-10 10:15 UTC
Labels: documentation
